name: Run integration tests chapter 6

on:
  workflow_call:
    inputs:
      lane:
        description: "Which lane to run (dev or latest)"
        required: true
        type: string
        default: 'latest'

  workflow_dispatch:
    inputs:
      lane:
        description: "Which lane to run (dev or latest)"
        required: true
        type: string
        default: 'latest'

permissions:
  contents: read


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: sindre-nistad/edc2026-workshop-containerised-integration-testing
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        working-directory: chapter_6
        run: |
          pip install -e ".[dev]"

      - name: Run integration tests with pytest
        working-directory: chapter_6

        run: |
          pytest -s .
